# roles/backend/tasks/main.yml
---


- name: Ensure .NET 6 SDK is installed
  apt:
    name: dotnet-sdk-6.0
    state: present
  become: yes

- name: Clone (or update) the mono-repo into /opt/DevOpsV1
  git:
    repo: https://github.com/DusanVukovic3/DevOpsV1.git
    dest: /opt/DevOpsV1
    version: main
    depth: 1
  become: yes

- name: Ensure the service directory (/opt/krecim) is clean
  file:
    path: /opt/krecim
    state: absent
  become: yes

- name: Recreate empty service directory (/opt/krecim)
  file:
    path: /opt/krecim
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'
  become: yes

- name: Publish only the BE project into /opt/krecim in Release mode
  command: >
    dotnet publish "MovieCollectionBE/MovieCollectionAPI.csproj" \
      -c Release \
      -o /opt/krecim
  args:
    chdir: /opt/DevOpsV1
  become: yes

- name: Restart the krecim systemd service
  systemd:
    name: krecim
    state: restarted
    enabled: yes
  become: yes

